apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  type: LoadBalancer
  selector:
    app: checkout-app
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5000
